name: android

on:
  release:
    types: [prereleased, released, published]
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - main
      - feature/*
  push:
    branches:
      - main
      - feature/*
  schedule:
    # GMT timezone.
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 30
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda #v3.4.2
      - name: Build with Gradle
        run: |
          cd starboard/android/apk
          ./gradlew build
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: |
            starboard/android/apk/app/build/outputs/apk/devel/*.apk
            starboard/android/apk/app/build/outputs/apk/release/*.apk
